# Generated by Django 3.0.6 on 2020-05-16 04:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('sitepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='page_content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='page_image',
            field=models.ForeignKey(blank=True, help_text='Primary Page Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
