# Generated by Django 3.0.6 on 2020-05-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepage', '0002_auto_20200516_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='newsletter_text',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='newsletter_title',
            field=models.CharField(default='Sign up for my newsletter', max_length=140),
        ),
    ]
