# Generated by Django 3.0.6 on 2020-05-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepage', '0003_auto_20200518_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepage',
            name='newsletter_text',
        ),
        migrations.RemoveField(
            model_name='sitepage',
            name='newsletter_title',
        ),
    ]
