# Generated by Django 3.0.6 on 2020-05-19 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('site_settings', '0002_footerimagesettings_newsletter_button_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterImageSettings',
            new_name='FooterSettings',
        ),
    ]
