# Generated by Django 3.0.5 on 2020-05-04 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_header',
            field=models.CharField(help_text='Header for the about page teaser', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='lead_text',
            field=models.CharField(help_text='Intro to about section text', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='top_image',
            field=models.ForeignKey(help_text='The top, primary image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
