# Generated by Django 3.0.5 on 2020-05-04 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0003_auto_20200504_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='linked_page',
            field=models.ForeignKey(blank=True, help_text='Select a page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='linked_page_text',
            field=models.CharField(default='Read More', help_text='Link text', max_length=50),
        ),
    ]
