# Generated by Django 3.0.6 on 2020-05-18 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0005_homepage_second_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section_button',
            field=models.ForeignKey(blank=True, help_text='Select a page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_button_text',
            field=models.CharField(default='Contact Me', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_title',
            field=models.CharField(default='Contact Me', max_length=250),
        ),
    ]
