# Generated by Django 3.0.6 on 2020-05-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerimagesettings',
            name='newsletter_button_text',
            field=models.URLField(default='Sign Me Up!'),
        ),
    ]
