# Generated by Django 3.0.6 on 2020-05-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20200519_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='newsletter_button_text',
            field=models.TextField(default='Sign Me Up!', max_length=50),
        ),
    ]
