# Generated by Django 3.0.6 on 2020-05-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menuitem_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='open_in_new_tab',
        ),
    ]
